/**
 * withLiveActivity.js
 *
 * Expo config plugin that wires up the JobRunner Live Activity widget extension.
 *
 * What this plugin does, in order:
 *   1. Adds `NSSupportsLiveActivities: true` to the HOST APP's Info.plist so
 *      the main app can register Live Activities at runtime.
 *   2. Adds an App Group entitlement (`group.com.jobrunner.app`) to the HOST
 *      APP so it can share data with the extension via the shared container.
 *   3. Copies the canonical Swift source files from
 *      `mobile/targets/JobRunnerLiveActivity/` into the generated
 *      `ios/JobRunnerLiveActivity/` folder. The `mobile/targets/` location is
 *      the source of truth (committed to git); `ios/` is regenerated by
 *      prebuild and not committed.
 *   4. Registers a new Xcode target (`JobRunnerLiveActivity`) as a Widget
 *      Extension embedded in the host app, with:
 *        - Bundle ID `com.jobrunner.app.liveactivity`
 *        - iOS Deployment Target 16.1 (Live Activities require 16.1+; host
 *          app stays at 16.0)
 *        - Swift 5.0
 *        - App Group entitlement (same group as the host)
 *        - Frameworks: SwiftUI, WidgetKit, ActivityKit
 *
 * This is the first plugin in this project that creates a new iOS extension
 * target. The Xcode-project manipulation in step 4 is the dense part — each
 * step is commented so future maintainers can read the plugin and understand
 * what's happening rather than reverse-engineering it from pbxproj diffs.
 *
 * Apple Developer portal prerequisites (must be in place before EAS will sign):
 *   1. App Group `group.com.jobrunner.app` exists.
 *   2. Main App ID `com.jobrunner.app` has App Groups capability enabled and
 *      ticks `group.com.jobrunner.app`.
 *   3. New App ID `com.jobrunner.app.liveactivity` exists with App Groups
 *      capability enabled and ticks `group.com.jobrunner.app`.
 *
 * Reference docs:
 *   - https://docs.expo.dev/config-plugins/introduction/
 *   - https://docs.expo.dev/config-plugins/mods/
 *   - https://developer.apple.com/documentation/activitykit
 */

const {
  withInfoPlist,
  withEntitlementsPlist,
  withXcodeProject,
  withDangerousMod,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const EXTENSION_NAME = "JobRunnerLiveActivity";
const EXTENSION_BUNDLE_ID = "com.jobrunner.app.liveactivity";
const APP_GROUP_ID = "group.com.jobrunner.app";
const EXTENSION_DEPLOYMENT_TARGET = "16.1";
const SWIFT_VERSION = "5.0";
const APPLE_TEAM_ID = "6557LUX45F";
const SOURCE_DIR_RELATIVE = path.join("targets", EXTENSION_NAME);

module.exports = function withLiveActivity(config) {
  config = withHostAppInfoPlist(config);
  config = withHostAppEntitlements(config);
  config = withCopyExtensionSources(config);
  config = withExtensionTarget(config);
  return config;
};

function withHostAppInfoPlist(config) {
  return withInfoPlist(config, (config) => {
    config.modResults.NSSupportsLiveActivities = true;
    return config;
  });
}

function withHostAppEntitlements(config) {
  return withEntitlementsPlist(config, (config) => {
    const key = "com.apple.security.application-groups";
    const existing = config.modResults[key] || [];
    if (!existing.includes(APP_GROUP_ID)) {
      config.modResults[key] = [...existing, APP_GROUP_ID];
    }
    return config;
  });
}

function withCopyExtensionSources(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const sourceDir = path.join(projectRoot, SOURCE_DIR_RELATIVE);
      const destDir = path.join(
        config.modRequest.platformProjectRoot,
        EXTENSION_NAME
      );
      if (!fs.existsSync(sourceDir)) {
        console.warn(`[withLiveActivity] Source directory missing: ${sourceDir}`);
        return config;
      }
      fs.rmSync(destDir, { recursive: true, force: true });
      fs.mkdirSync(destDir, { recursive: true });
      fs.cpSync(sourceDir, destDir, { recursive: true });
      console.log(`[withLiveActivity] Copied sources: ${sourceDir} -> ${destDir}`);
      return config;
    },
  ]);
}

function withExtensionTarget(config) {
  return withXcodeProject(config, async (config) => {
    const proj = config.modResults;

    if (proj.pbxTargetByName(EXTENSION_NAME)) {
      console.log(`[withLiveActivity] Target ${EXTENSION_NAME} already present — skipping.`);
      return config;
    }

    const groupChildren = listExtensionSourceFiles(config);
    const pbxGroup = proj.addPbxGroup(groupChildren, EXTENSION_NAME, EXTENSION_NAME);
    const mainGroupUuid = proj.getFirstProject().firstProject.mainGroup;
    proj.addToPbxGroup(pbxGroup.uuid, mainGroupUuid);

    const target = proj.addTarget(
      EXTENSION_NAME,
      "app_extension",
      EXTENSION_NAME,
      EXTENSION_BUNDLE_ID
    );

    const swiftSources = groupChildren.filter((f) => f.endsWith(".swift"));
    proj.addBuildPhase(swiftSources, "PBXSourcesBuildPhase", "Sources", target.uuid);

    const resourceFiles = groupChildren.filter(
      (f) => f.endsWith(".xcassets") || (f.endsWith(".plist") && !f.endsWith("Info.plist"))
    );
    proj.addBuildPhase(resourceFiles, "PBXResourcesBuildPhase", "Resources", target.uuid);

    proj.addBuildPhase(
      ["SwiftUI.framework", "WidgetKit.framework", "ActivityKit.framework"],
      "PBXFrameworksBuildPhase",
      "Frameworks",
      target.uuid
    );

    // addTarget() auto-creates an embed phase — just ensure CodeSignOnCopy is set
    const buildFiles = proj.pbxBuildFileSection();
    for (const uuid in buildFiles) {
      const bf = buildFiles[uuid];
      if (typeof bf !== "object") continue;
      if (!bf.fileRef_comment || !bf.fileRef_comment.includes(EXTENSION_NAME)) continue;
      bf.settings = bf.settings || {};
      const attrs = bf.settings.ATTRIBUTES || [];
      if (!attrs.includes("CodeSignOnCopy")) {
        bf.settings.ATTRIBUTES = [...attrs, "CodeSignOnCopy"];
      }
    }

    const hostTargetUuid = proj.getFirstTarget().uuid;
    proj.addTargetDependency(hostTargetUuid, [target.uuid]);
    applyExtensionBuildSettings(proj, target);

    console.log(`[withLiveActivity] Registered Xcode target: ${EXTENSION_NAME}`);
    return config;
  });
}

function listExtensionSourceFiles(config) {
  const sourceDir = path.join(config.modRequest.projectRoot, SOURCE_DIR_RELATIVE);
  if (!fs.existsSync(sourceDir)) return [];
  return fs.readdirSync(sourceDir).filter((f) => !f.startsWith("."));
}

function applyExtensionBuildSettings(proj, target) {
  const allConfigs = proj.pbxXCBuildConfigurationSection();
  const configListUuid = target.pbxNativeTarget.buildConfigurationList;
  const configList = proj.pbxXCConfigurationList()[configListUuid];
  const configUuids = configList.buildConfigurations.map((bc) => bc.value);

  for (const uuid of configUuids) {
    const conf = allConfigs[uuid];
    if (!conf || typeof conf === "string") continue;
    const s = conf.buildSettings;
    s.IPHONEOS_DEPLOYMENT_TARGET = EXTENSION_DEPLOYMENT_TARGET;
    s.SWIFT_VERSION = SWIFT_VERSION;
    s.PRODUCT_BUNDLE_IDENTIFIER = EXTENSION_BUNDLE_ID;
    s.CODE_SIGN_ENTITLEMENTS = `${EXTENSION_NAME}/${EXTENSION_NAME}.entitlements`;
    s.INFOPLIST_FILE = `${EXTENSION_NAME}/Info.plist`;
    s.CODE_SIGN_STYLE = "Automatic";
    s.DEVELOPMENT_TEAM = APPLE_TEAM_ID;
    s.TARGETED_DEVICE_FAMILY = `"1,2"`;
    s.PRODUCT_NAME = `"$(TARGET_NAME)"`;
    s.SKIP_INSTALL = "NO";
    s.ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = "NO";
  }
}